# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    boot.initrd.kernelModules = [ "dm-snapshot" ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.initrd.luks.devices = {
        root = { 
            device = "/dev/disk/by-uuid/b9778859-81fd-4d5c-9e4d-c57d05d6aacd";
            preLVM = true;
        };
    };

    fileSystems."/" = { 
        device = "/dev/disk/by-uuid/55848a5b-3ed7-401c-b882-3d2c8ffae136";
        fsType = "btrfs";
    };

    fileSystems."/home" = {
        device = "/dev/disk/by-uuid/06c0c17e-87c3-4411-8897-52aadfbd5023";
        fsType = "btrfs";
	options = [ "subvol=@home" "compress=zstd "];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/010C-EC52";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
    };

    swapDevices = [ 
        {
            device = "/dev/disk/by-uuid/188e4022-22cb-4af4-b7d3-ad66c8ef11c2";
        }
    ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp109s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
